main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Resume
    url: '/uploads/resume.pdf'
    weight: 40